INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (1,3,'2024-12-12','A');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (1,5,'2024-12-13','B');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (2,3,'2024-12-12','C');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (2,6,'2024-12-13','A');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (3,3,'2024-12-12','B');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (3,4,'2024-12-13','A');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (4,2,'2024-12-12','B');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (4,5,'2024-12-13','A');
INSERT INTO course_detail (student_id,course_id, enrollment_date,grade) Values (4,6,'2024-12-13','C');
